---
- name: 檢示特定的 AWS S3 儲存貯體
  hosts: localhost
  connection: local
  gather_facts: false

  vars:
    # bucket_name: "king610160-test-bucket-5"
    aws_region: "ap-northeast-1"

  tasks:
    - name: get s3 bucket
      amazon.aws.s3_bucket:
        name: "{{ bucket_name }}"
        region: "{{ aws_region }}"
      register: bucket_result

    - name: show result
      ansible.builtin.debug:
        msg: "{{ bucket_result }}"